---
title: "R Notebook"
output: html_notebook
---



```{r}
library(tidyverse)
library(tabulizer)
```
```{r}
read_table <- function(header)
{
  all_frames = list()
  for(year in c(2019, 2023))
  {
    for(fname in list.files(as.character(year), '*.pdf'))
    {
      bydel <- fname |> str_replace("Valgprotokoll_bydelsutvalg_", "") |> str_replace(" 2019.pdf", "")  |> str_replace("Bydel ", "") |> str_replace(" - valgprotokoll.pdf", "")
      tbls <- extract_tables(paste0(as.character(year), "/", fname), output="data.frame")
      for(tbl in tbls)
      {
        if(identical(colnames(tbl), header))
        {
          break;
        }
      }
      tbl <- tbl |> mutate(year=year, bydel=bydel)
      all_frames <- append(all_frames, list(tbl))
    }
    
  }
  return(bind_rows(all_frames))
}
```


```{r}
partioppslutning <- read_table(c("Parti", "Forhånd", "Valgting", "Total"))
partioppslutning

```

```{r}
bydel_info <- "bydel,gjennomsnittsinntekt
Gamle Oslo,495000
Grünerløkka,488000
Sagene,507000
St. Hanshaugen,516000
Frogner,711000
Ullern,812000
Vestre Aker,882000
Nordre Aker,640000
Bjerke,471000
Grorud,407000
Stovner,391000
Alna,415000
Østensjø,524000
Nordstrand,666000
Søndre Nordstrand,410000
"

bydel_stats <- read_csv(bydel_info, col_types=c("c", "n")) |> mutate(bydel=fct_reorder(bydel, gjennomsnittsinntekt))
```

```{r}
parti_info <- "parti,parti_kort,politisk_pos
Rødt,R,0
SV - Sosialistisk Venstreparti,SV,1
Arbeiderpartiet,Ap,2
Miljøpartiet De Grønne,MDG,3
Senterpartiet,Sp,4
Partiet Sentrum,PS,5
Venstre,V,6
Kristelig Folkeparti,KrF,7
Høyre,H,8
Fremskrittspartiet,FrP,9
Partiet Mot Bompenger,FNB,10
Industri- og Næringspartiet,INP,11
"

parti_stats <- read_csv(parti_info, col_types=c("c", "c", "i")) |> mutate(parti=fct_reorder(parti,politisk_pos), parti_kort=fct_reorder(parti_kort, politisk_pos))
```





```{r}
dftmp <- partioppslutning |> janitor::clean_names() |> filter(parti != "Totalt antall partifordelte stemmesedler") |> dplyr::rename(stemmer=total)
df <- dftmp |> group_by(year, bydel) |> summarise(total_stemmer = sum(stemmer), .groups="drop") |> left_join(dftmp, by = join_by(year, bydel)) |> mutate(stemmeandel = stemmer/total_stemmer) |> left_join(bydel_stats, by=join_by(bydel)) |> right_join(parti_stats, by=join_by(parti)) |> mutate(bydel = fct_reorder(bydel, gjennomsnittsinntekt)) 
```

```{r}
write_csv(df, "datasett.csv")
```


```{r}
(ggplot(df |> filter(parti=="Rødt") |> mutate(bydel = fct_reorder(bydel, gjennomsnittsinntekt)) |> mutate(year=fct_rev(as.factor(year))), aes(x=gjennomsnittsinntekt, y=stemmeandel, colour=year))
                                + geom_point()
 + scale_y_continuous(labels = scales::percent, breaks=scales::pretty_breaks(8))
 + expand_limits(y=0)
 + theme_minimal()
 + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
 )
```

```{r fig.width=10}
(ggplot(df |> mutate(year=fct_rev(as.factor(year))), aes(x=bydel, y=stemmeandel, colour=year))
 + geom_point()
 + geom_line(color="black", arrow = arrow(length = unit(0.15, "cm")), linewidth=0.2)
 + scale_y_continuous(labels = scales::percent, breaks=scales::pretty_breaks(4))
 + expand_limits(y=0)
 + theme_minimal()
 + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
 + facet_wrap(parti_kort ~ ., scales="free_y")
 + labs(title="Stemmeandel per parti i bydelsvalg, 2019→2023", subtitle="Bydeler sortert etter gjennomsnittsinntekt", y="Stemmeandel", x="Bydel", color="År")
 )
```




```{r fig.width=10}
(ggplot(df |> filter(year==2023), aes(x=gjennomsnittsinntekt, y=stemmeandel, label=bydel))
                                + geom_point()
 #+ geom_text()
 + scale_y_continuous(labels = scales::percent, breaks=scales::pretty_breaks(4))
 + scale_x_continuous(labels = scales::label_comma(big.mark=" "))
 + expand_limits(y=0)
 + theme_minimal()
 + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
 + facet_wrap(parti_kort ~ ., scales="free_y")
 )
```

```{r fig.width=10}
(ggplot(df |> mutate(year=fct_rev(as.factor(year))), aes(x=bydel, y=stemmer, colour=year))
 + geom_point()
 + geom_line(color="black", arrow = arrow(length = unit(0.15, "cm")), linewidth=0.2)
 + scale_y_continuous(labels = scales::label_number(big.mark=" "), breaks=scales::pretty_breaks(4))
 + expand_limits(y=0)
 + theme_minimal()
 + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
 + facet_wrap(parti_kort ~ ., scales="free_y")
 + labs(title="Stemmetall per parti i bydelsvalg, 2019→2023", subtitle="Bydeler sortert etter gjennomsnittsinntekt", y="Stemmer", x="Bydel", color="År")
 )

```

```{r fig.width=8}
(ggplot(df |> group_by(year, bydel) |> summarise(total_stemmer=mean(total_stemmer), .groups="drop")  |> mutate(year=fct_rev(as.factor(year))), aes(x=bydel, y=total_stemmer, colour=year))
 + geom_point()
 + geom_line(color="black", arrow = arrow(length = unit(0.15, "cm")), linewidth=0.2)
 + scale_y_continuous(labels = scales::label_number(big.mark=" "), breaks=scales::pretty_breaks(6))
 + expand_limits(y=0)
 + theme_minimal()
 + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
 + labs(title="Totalt antall stemmer per bydel bydelsvalg, 2019→2023", subtitle="Bydeler sortert etter gjennomsnittsinntekt", y="Totale gyldige stemmer", x="Bydel", color="År")
 )

```